name:                haskell-training
version:             0.1.0.0
github:              "thomasvergne/haskell-training"
license:             BSD3
author:              "Thomas"
maintainer:          "thomas@quark-lang.dev"
copyright:           "2021 Thomas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thomasvergne/haskell-training#readme>

dependencies:
- base >= 4.7 && < 5
- numeric-prelude

library:
  source-dirs: src

executables:
  haskell-training-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-training

tests:
  haskell-training-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-training
